# Generated by Django 5.2.9 on 2025-12-29 19:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoiDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ten_goi', models.CharField(max_length=200)),
                ('loai_goi', models.CharField(choices=[('noi_bat_tin', 'Tin tuyển dụng nổi bật'), ('uu_tien_ho_so', 'Hồ sơ ứng viên ưu tiên'), ('dang_nhieu_tin', 'Đăng nhiều tin tuyển dụng')], max_length=30)),
                ('mo_ta', models.TextField()),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('thoi_han_ngay', models.IntegerField(verbose_name='Thời hạn (ngày)')),
                ('tinh_nang', models.TextField(verbose_name='Các tính năng')),
            ],
            options={
                'verbose_name': 'Gói dịch vụ',
                'verbose_name_plural': 'Gói dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='NganhNghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ten', models.CharField(max_length=255, unique=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
            ],
            options={
                'verbose_name': 'Ngành nghề',
                'verbose_name_plural': 'Ngành nghề',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('vai_tro', models.CharField(choices=[('admin', 'Quản trị viên'), ('nha_tuyen_dung', 'Nhà tuyển dụng'), ('ung_vien', 'Ứng viên')], default='ung_vien', max_length=20)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giao_dich', models.CharField(max_length=100, unique=True)),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12)),
                ('phuong_thuc', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay')], max_length=20)),
                ('trang_thai', models.CharField(choices=[('cho_thanh_toan', 'Chờ thanh toán'), ('thanh_cong', 'Thành công'), ('that_bai', 'Thất bại'), ('hoan_tien', 'Hoàn tiền')], default='cho_thanh_toan', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_thanh_toan', models.DateTimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_dich', to=settings.AUTH_USER_MODEL)),
                ('goi_dich_vu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findwork.goidichvu')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='NhaTuyenDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ten_cong_ty', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('logo', models.ImageField(upload_to='uploads/%Y/%m')),
                ('ma_so_thue', models.CharField(max_length=50, unique=True, verbose_name='Mã số thuế')),
                ('linh_vuc', models.CharField(max_length=200, verbose_name='Lĩnh vực hoạt động')),
                ('quy_mo', models.CharField(max_length=100, verbose_name='Quy mô nhân sự')),
                ('mo_ta', models.TextField(verbose_name='Mô tả công ty')),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20)),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True)),
                ('nguoi_duyet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nha_tuyen_dung_da_duyet', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhà tuyển dụng',
                'verbose_name_plural': 'Nhà tuyển dụng',
            },
        ),
        migrations.CreateModel(
            name='TinTuyenDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tieu_de', models.CharField(max_length=300, verbose_name='Tiêu đề tuyển dụng')),
                ('mo_ta_cong_viec', models.TextField(verbose_name='Mô tả công việc')),
                ('yeu_cau', models.TextField(verbose_name='Yêu cầu ứng viên')),
                ('muc_luong_tu', models.DecimalField(decimal_places=0, max_digits=15)),
                ('muc_luong_den', models.DecimalField(decimal_places=0, max_digits=15)),
                ('don_vi_luong', models.CharField(default='VNĐ', max_length=50)),
                ('dai_ngo', models.TextField(verbose_name='Chế độ đãi ngộ')),
                ('dia_diem', models.CharField(max_length=300, verbose_name='Địa điểm làm việc')),
                ('so_luong_tuyen', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('han_nop_ho_so', models.DateField(verbose_name='Hạn nộp hồ sơ')),
                ('trang_thai', models.CharField(choices=[('dang_tuyen', 'Đang tuyển'), ('het_han', 'Hết hạn'), ('dong', 'Đã đóng')], default='dang_tuyen', max_length=20)),
                ('tin_noi_bat', models.BooleanField(default=False)),
                ('nga_het_han_noi_bat', models.DateTimeField(blank=True, null=True)),
                ('luot_xem', models.IntegerField(default=0)),
                ('nganh_nghe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tin_tuyen_dung', to='findwork.nganhnghe')),
                ('nha_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_tuyen_dung', to='findwork.nhatuyendung')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Tin tuyển dụng',
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='UngVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ho_ten', models.CharField(max_length=200)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=10)),
                ('trinh_do', models.CharField(max_length=100, verbose_name='Trình độ học vấn')),
                ('kinh_nghiem', models.CharField(max_length=100, verbose_name='Kinh nghiem')),
                ('mo_ta_ban_than', models.TextField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m', verbose_name='File CV')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ung_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoSanhCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('tin_tuyen_dung', models.ManyToManyField(related_name='duoc_so_sanh', to='findwork.tintuyendung')),
                ('ung_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_sanh', to='findwork.ungvien')),
            ],
            options={
                'verbose_name': 'So sánh công việc',
                'verbose_name_plural': 'So sánh công việc',
            },
        ),
        migrations.CreateModel(
            name='HoSoUngTuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ngay_nop', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('moi_nop', 'Mới nộp'), ('da_xem', 'Đã xem'), ('phu_hop', 'Phù hợp'), ('khong_phu_hop', 'Không phù hợp'), ('phong_van', 'Mời phỏng vấn'), ('trung_tuyen', 'Trúng tuyển'), ('tu_choi', 'Từ chối')], default='moi_nop', max_length=20)),
                ('cv_dinh_kem', models.FileField(blank=True, null=True, upload_to='cv_dinh')),
                ('danh_gia', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ghi_chu_nha_tuyen_dung', models.TextField(blank=True)),
                ('tin_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so', to='findwork.tintuyendung')),
                ('ung_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_ung_tuyen', to='findwork.ungvien')),
            ],
            options={
                'verbose_name': 'Hồ sơ ứng tuyển',
                'verbose_name_plural': 'Hồ sơ ứng tuyển',
                'ordering': ['-ngay_nop'],
                'unique_together': {('tin_tuyen_dung', 'ung_vien')},
            },
        ),
    ]
