# Generated by Django 5.2.9 on 2025-12-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ungvien',
            options={'verbose_name': 'Ứng viên', 'verbose_name_plural': 'Ứng viên'},
        ),
        migrations.AddField(
            model_name='ungvien',
            name='ky_nang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
