# Generated by Django 5.2.9 on 2025-12-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0002_alter_ungvien_options_ungvien_ky_nang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tintuyendung',
            old_name='nga_het_han_noi_bat',
            new_name='ngay_het_han_noi_bat',
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='tieu_de',
            field=models.CharField(max_length=300, verbose_name='Vị trí'),
        ),
    ]
