# Generated by Django 5.2.9 on 2025-12-30 18:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0003_rename_nga_het_han_noi_bat_tintuyendung_ngay_het_han_noi_bat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaodich',
            name='ghi_chu',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goidichvu',
            name='mo_ta',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='goidichvu',
            name='tinh_nang',
            field=ckeditor.fields.RichTextField(verbose_name='Các tính năng'),
        ),
        migrations.AlterField(
            model_name='hosoungtuyen',
            name='ghi_chu_nha_tuyen_dung',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nganhnghe',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='nganhnghe/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='nganhnghe',
            name='mo_ta',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nhatuyendung',
            name='logo',
            field=models.ImageField(upload_to='nhatuyendung/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='nhatuyendung',
            name='mo_ta',
            field=ckeditor.fields.RichTextField(verbose_name='Mô tả công ty'),
        ),
        migrations.AlterField(
            model_name='sosanhcongviec',
            name='ghi_chu',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='dai_ngo',
            field=ckeditor.fields.RichTextField(verbose_name='Chế độ đãi ngộ'),
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='mo_ta_cong_viec',
            field=ckeditor.fields.RichTextField(verbose_name='Mô tả công việc'),
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='yeu_cau',
            field=ckeditor.fields.RichTextField(verbose_name='Yêu cầu ứng viên'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='ungvien/%Y/%m', verbose_name='File CV'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='ky_nang',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='findwork/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dia_chi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
