# Generated by Django 5.2.9 on 2026-01-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0004_alter_giaodich_ghi_chu_alter_goidichvu_mo_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
