# Generated by Django 5.2.9 on 2026-01-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
