# Generated by Django 5.2.9 on 2026-01-14 12:00

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatuyendung',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nha_tuyen_dung', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='dai_ngo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Chế độ đãi ngộ'),
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='mo_ta_cong_viec',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Mô tả công việc'),
        ),
        migrations.AlterField(
            model_name='tintuyendung',
            name='yeu_cau',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Yêu cầu ứng viên'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='cv_file',
            field=models.ImageField(blank=True, null=True, upload_to='ungvien/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m'),
        ),
    ]
